"""empty message

Revision ID: 3254fb588813
Revises: 2a4ac00d47f0
Create Date: 2020-05-08 21:46:27.701263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3254fb588813'
down_revision = '2a4ac00d47f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('username', sa.String(length=50), nullable=False))
    op.drop_column('cms_user', 'usename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('usename', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('cms_user', 'username')
    # ### end Alembic commands ###
